package org.db2code.generator.java.pojo.adapter;

import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.Collection;
import java.util.stream.Collectors;
import org.db2code.convert.JavaPropertyConverter;
import org.db2code.rawmodel.RawTable;

public class JavaClassAdapter {
    private final RawTable rawTable;
    private final String targetPackage;
    private final DateImpl dateImpl;
    private final boolean includeGenerationInfo;

    public JavaClassAdapter(
            RawTable rawTable,
            String targetPackage,
            DateImpl dateImpl,
            boolean includeGenerationInfo) {
        this.rawTable = rawTable;
        this.targetPackage = targetPackage;
        this.dateImpl = dateImpl;
        this.includeGenerationInfo = includeGenerationInfo;
    }

    public String getClassName() {
        return JavaPropertyConverter.camelCaseFromSnakeCaseInitCap(rawTable.getTableName());
    }

    public RawTable getRawTable() {
        return rawTable;
    }

    public String getPackage() {
        return targetPackage;
    }

    public Collection<JavaPropertyAdapter> getProperties() {
        return rawTable.getColumns().stream()
                .map(rawColumn -> new JavaPropertyAdapter(rawTable, rawColumn, dateImpl))
                .collect(Collectors.toList());
    }

    public String getGenerationInfo() {
        if (includeGenerationInfo) {
            return "Generated by DB2Code at: "
                    + LocalDateTime.now(ZoneId.systemDefault()).toString();
        } else {
            return null;
        }
    }
}
